steps:
  # Build Docker image for BigQuery update
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/airy-parsec-400006/test-build/bigquery-image:$SHORT_SHA'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/airy-parsec-400006/test-build/bigquery-image:$SHORT_SHA'

  # Execute
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - "-c"
      - |
        cd /workspace
        echo "Fetching changed files..."
        git fetch --depth=2 origin main
        
        
        # Get the list of changed files between the latest commit and the previous commit
        git diff --name-only HEAD~1 HEAD | while read -r file; do
          echo "Processing file: $file"
          if [[ "$file" =~ .*\.sql$ ]]; then
          # if [[ "$file" =~ ^source/.*\.sql$ || "$file" =~ ^historical/.*\.sql$ || "$file" =~ ^test/.*\.sql$ ]]; then
            echo "Running SQL query from file: $file"
            bq query --use_legacy_sql=false --format=none \
              "$(cat $file)"
          fi
        done

images:
  - 'us-central1-docker.pkg.dev/airy-parsec-400006/test-build/bigquery-image:$SHORT_SHA'


timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

