steps:
  # Step to deploy or update a Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - testing-functions-build
      - --runtime=python310   
      - --trigger-http        
      - --allow-unauthenticated 
      - --source=cloud_functions/ 
      - --region=us-central1  

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY