steps:
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       # Go to the folder containing the SQL file
  #       cd sql
  #       # Run BigQuery query using 'bq'
  #       bq query --use_legacy_sql=false --format=none \
  #         "$(cat view_script.sql)"
    # - '--file=sql/view_script.sql'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        echo "Fetching changed files..."
        git fetch --depth=2 origin main
        gcloud builds submit --config=cloudbuild-bigquery.yaml \
  --substitutions=_CHANGED_FILES="$(git diff --name-only HEAD~1 HEAD)",_SQL_FILES_TO_PROCESS="vikas"
        # $_CHANGED_FILES='vikas'
        # echo '$_CHANGED_FILES'
        # $_CHANGED_FILES='$(git diff --name-only HEAD~1 HEAD)'
        echo "Changed files: $_CHANGED_FILES"
        # Get the list of changed files between the latest commit and the previous commit
        # git diff --name-only HEAD~1 HEAD | while read -r file; do
        #   echo "Processing file: $file"
        #   if [[ "$file" =~ .*\.sql$ ]]; then
        #   # if [[ "$file" =~ ^source/.*\.sql$ || "$file" =~ ^historical/.*\.sql$ || "$file" =~ ^test/.*\.sql$ ]]; then
        #     $_SQL_FILES_TO_PROCESS="$_SQL_FILES_TO_PROCESS $file"
        #   fi
        # done
        echo "Changed SQL files: $_SQL_FILES_TO_PROCESS" 

  #       # Save the list of changed files to a workspace file
  #       # echo "$CHANGED_FILES" > /workspace/changed_files.txt
        
  #       # CHANGED_FILES=$(cat /workspace/changed_files.txt)
  #       # Initialize an empty list of files to process
        # _SQL_FILES_TO_PROCESS=""

  #       # Identify which files are SQL files in specific folders
  #       for file in $CHANGED_FILES; do
  #         if [[ "$file" =~ .*\.sql$ ]]; then
  #         # if [[ "$file" =~ ^source/.*\.sql$ || "$file" =~ ^historical/.*\.sql$ || "$file" =~ ^test/.*\.sql$ ]]; then
  #           _SQL_FILES_TO_PROCESS="$_SQL_FILES_TO_PROCESS $file"
  #         fi
  #       done

        # Check if there are any SQL files to process
        # if [ -z "$_SQL_FILES_TO_PROCESS" ]; then
        #   echo "No SQL files changed. Exiting."
        #   exit 0
        # else
        #   echo "Changed SQL files: $_SQL_FILES_TO_PROCESS"
        # fi

  # # Run each SQL file in BigQuery
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       # For each SQL file, run the corresponding query in BigQuery
  #       for file in $_SQL_FILES_TO_PROCESS; do
  #         echo "Running SQL query from file: $file"
  #         bq query --use_legacy_sql=false --format=none \
  #           "$(cat $file)"
  #       done


substitutions:
  _SQL_FILES_TO_PROCESS: ''
  _CHANGED_FILES: ''
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

