steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        git fetch --depth=2 origin main
        git diff --name-only HEAD~1 HEAD | while read -r file; do
          if [[ "$file" =~ ^composer/dags/.*\.py$ ]]; then
            echo "Uploading $file to gs://$_BUCKET_NAME/$file..."
            gsutil cp $file gs://$_BUCKET_NAME/dags/$(basename "$file")
          fi
        done


  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VARIABLES=$(cat composer/variables/env_variables.json | jq -r 'to_entries | map("\(.key)=\(.value)") | join(",")')
        gcloud composer environments update testing-cloudbuild \
          --location us-central1 \
          --update-env-variables $VARIABLES


  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       echo "Refreshing Composer DAGs..."
  #       gcloud composer environments update your-environment-name \
  #         --location your-region \
  #         --update-labels=updated=true

substitutions:
  _DAG_FILES: ''
  _CHANGED_FILES: ''
  _BUCKET_NAME: 'us-central1-testing-cloudbu-c3b2633c-bucket'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
