steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git fetch --depth=2 origin main
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
        DAG_FILES=""
        for file in $CHANGED_FILES; do
          if [[ "$file" =~ ^composer/dags/.*\.py$]]; then
            DAG_FILES="$DAG_FILES $file"
          fi
        done

        if [ -z "$DAG_FILES" ]; then
          echo "No DAG files changed. Exiting..."
          exit 0
        fi

        BUCKET_NAME="us-central1-testing-cloudbu-c3b2633c-bucket"
        for file in $DAG_FILES; do
          echo "Uploading $file to gs://$BUCKET_NAME/$file..."
          gsutil cp $file gs://$BUCKET_NAME/$file
        done

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Refreshing Composer DAGs..."
        gcloud composer environments update your-environment-name \
          --location your-region \
          --update-labels=updated=true

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
