steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        git fetch --depth=2 origin main
        _CHANGED_FILES="$(git diff --name-only HEAD~1 HEAD)"

        # Save the list of changed files to a workspace file
        # echo "$_CHANGED_FILES" > /workspace/_CHANGED_FILES.txt
      
        for file in $_CHANGED_FILES; do
          if [[ "$file" =~ ^composer/dags/.*\.py$]]; then
            _DAG_FILES="$_DAG_FILES $file"
          fi
        done

        if [ -z "$_DAG_FILES" ]; then
          echo "No DAG files changed. Exiting..."
          exit 0
        fi

        for file in $_DAG_FILES; do
          echo "Uploading $file to gs://$_BUCKET_NAME/$file..."
          gsutil cp $file gs://$_BUCKET_NAME/$file
        done

  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       echo "Refreshing Composer DAGs..."
  #       gcloud composer environments update your-environment-name \
  #         --location your-region \
  #         --update-labels=updated=true

substitutions:
  _DAG_FILES: ''
  _CHANGED_FILES: ''
  __BUCKET_NAME: 'us-central1-testing-cloudbu-c3b2633c-bucket'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
