steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - "bash"
      - "-c"
      - |
        cd /workspace
        echo "Fetching changed files..."
        git fetch --depth=2 origin main
        
        
        # Get the list of changed files between the latest commit and the previous commit
        git diff --name-only HEAD~1 HEAD | while read -r file; do
          echo "Processing file: $file"
          if [[ "$file" =~ .*\.sql$ ]]; then
          # if [[ "$file" =~ ^source/.*\.sql$ || "$file" =~ ^historical/.*\.sql$ || "$file" =~ ^test/.*\.sql$ ]]; then
            echo "Running SQL query from file: $file"
            bq query --use_legacy_sql=false --format=none \
              "$(cat $file)"
          fi
        done


timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY

