steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        git fetch --depth=2 origin main
        git diff --name-only HEAD~1 HEAD | while read -r file; do
          if [ "$file" =~ ^composer/dags/.*\.py$]; then
            echo "Uploading $file to gs://$_BUCKET_NAME/$file..."
            gsutil cp $file gs://$_BUCKET_NAME/$file
          fi
        done


  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       echo "Refreshing Composer DAGs..."
  #       gcloud composer environments update your-environment-name \
  #         --location your-region \
  #         --update-labels=updated=true

substitutions:
  _DAG_FILES: ''
  _CHANGED_FILES: ''
  __BUCKET_NAME: 'us-central1-testing-cloudbu-c3b2633c-bucket'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
