steps:
  # Deploy the Cloud Function from the GitHub repository.
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   args: ['gcloud', 'functions', 'deploy', 'test-build', '--runtime', 'python310', '--trigger-http', '--allow-unauthenticated', '--source', './cloud_functions']

  # Install dependencies
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['pip', 'install', '-r', 'requirements.txt']
    dir: './cloud_functions'

timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY