steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Run BigQuery query using 'bq'
        bq query --use_legacy_sql=false --format=none \
          "SELECT 1;"
    # - '--file=sql/view_script.sql'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
