steps:
- name: 'gcr.io/community-builders/bq'
  args:
    - 'query'
    - '--use_legacy_sql=false'
    - '--format=none'
    - |
      SELECT 1;
    # - '--file=sql/view_script.sql'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
